name: MaskShopUI
version: 1.0
main: Kylan1940\MaskShopUI\Main
api: 4.0.0
author: Kylan1940

commands:
  mask:
   description: open mask shop in ui
   usage: "/mask"
   permission: mask.shop
permissions:
  mask.shop:
   default: true
   description: allow user open mask shop 
